# Generated by Django 5.0.6 on 2024-07-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='title',
        ),
        migrations.AddField(
            model_name='userpost',
            name='post_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
